#!/bin/sh
# Run each test and compare
# against known good output

if [ ! -f ../target/debug/crust ]
then echo "Need to build the compiler first!"; exit 1
fi

for i in test*
do if [ ! -f "out.$i" ]
   then echo "Can't run test on $i, no output file!"
   else
     echo -n $i
     ../target/debug/crust $i
    #  nasm -f elf64 out.s
     cc -no-pie -o out out.s
     ./out > trial.$i
     cmp -s "out.$i" "trial.$i"
     if [ "$?" -eq "1" ]
     then echo ": failed"
       diff -c "out.$i" "trial.$i"
       echo
     else echo ": OK"
     fi
     rm -f out out.o out.s "trial.$i"
   fi
done